INSERT ALL 
INTO tbl_countries (CODE, NAME) VALUES ('AFG', 'Afghanistan') 
INTO tbl_countries (CODE, NAME) VALUES ('ALB', 'Albania') 
INTO tbl_countries (CODE, NAME) VALUES ('DZA', 'Algeria') 
INTO tbl_countries (CODE, NAME) VALUES ('ASM', 'American Samoa') 
INTO tbl_countries (CODE, NAME) VALUES ('AND', 'Andorra') 
INTO tbl_countries (CODE, NAME) VALUES ('AGO', 'Angola') 
INTO tbl_countries (CODE, NAME) VALUES ('ATG', 'Antigua and Barbuda') 
INTO tbl_countries (CODE, NAME) VALUES ('ARG', 'Argentina') 
INTO tbl_countries (CODE, NAME) VALUES ('ARM', 'Armenia') 
INTO tbl_countries (CODE, NAME) VALUES ('ABW', 'Aruba') 
INTO tbl_countries (CODE, NAME) VALUES ('AUS', 'Australia') 
INTO tbl_countries (CODE, NAME) VALUES ('AUT', 'Austria') 
INTO tbl_countries (CODE, NAME) VALUES ('AZE', 'Azerbaijan') 
INTO tbl_countries (CODE, NAME) VALUES ('BHS', 'Bahamas, The') 
INTO tbl_countries (CODE, NAME) VALUES ('BHR', 'Bahrain') 
INTO tbl_countries (CODE, NAME) VALUES ('BGD', 'Bangladesh') 
INTO tbl_countries (CODE, NAME) VALUES ('BRB', 'Barbados') 
INTO tbl_countries (CODE, NAME) VALUES ('BLR', 'Belarus') 
INTO tbl_countries (CODE, NAME) VALUES ('BEL', 'Belgium') 
INTO tbl_countries (CODE, NAME) VALUES ('BLZ', 'Belize') 
INTO tbl_countries (CODE, NAME) VALUES ('BEN', 'Benin') 
INTO tbl_countries (CODE, NAME) VALUES ('BMU', 'Bermuda') 
INTO tbl_countries (CODE, NAME) VALUES ('BTN', 'Bhutan') 
INTO tbl_countries (CODE, NAME) VALUES ('BOL', 'Bolivia') 
INTO tbl_countries (CODE, NAME) VALUES ('BIH', 'Bosnia and Herzegovina') 
INTO tbl_countries (CODE, NAME) VALUES ('BWA', 'Botswana') 
INTO tbl_countries (CODE, NAME) VALUES ('BRA', 'Brazil') 
INTO tbl_countries (CODE, NAME) VALUES ('VGB', 'British Virgin Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('BRN', 'Brunei Darussalam') 
INTO tbl_countries (CODE, NAME) VALUES ('BGR', 'Bulgaria') 
INTO tbl_countries (CODE, NAME) VALUES ('BFA', 'Burkina Faso') 
INTO tbl_countries (CODE, NAME) VALUES ('BDI', 'Burundi') 
INTO tbl_countries (CODE, NAME) VALUES ('CPV', 'Cabo Verde') 
INTO tbl_countries (CODE, NAME) VALUES ('KHM', 'Cambodia') 
INTO tbl_countries (CODE, NAME) VALUES ('CMR', 'Cameroon') 
INTO tbl_countries (CODE, NAME) VALUES ('CAN', 'Canada') 
INTO tbl_countries (CODE, NAME) VALUES ('CYM', 'Cayman Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('CAF', 'Central African Republic') 
INTO tbl_countries (CODE, NAME) VALUES ('TCD', 'Chad') 
INTO tbl_countries (CODE, NAME) VALUES ('CHI', 'Channel Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('CHL', 'Chile') 
INTO tbl_countries (CODE, NAME) VALUES ('CHN', 'China') 
INTO tbl_countries (CODE, NAME) VALUES ('COL', 'Colombia') 
INTO tbl_countries (CODE, NAME) VALUES ('COM', 'Comoros') 
INTO tbl_countries (CODE, NAME) VALUES ('COD', 'Congo, Dem. Rep.') 
INTO tbl_countries (CODE, NAME) VALUES ('COG', 'Congo, Rep.') 
INTO tbl_countries (CODE, NAME) VALUES ('CRI', 'Costa Rica') 
INTO tbl_countries (CODE, NAME) VALUES ('CIV', 'Ivory Coast') 
INTO tbl_countries (CODE, NAME) VALUES ('HRV', 'Croatia') 
INTO tbl_countries (CODE, NAME) VALUES ('CUB', 'Cuba') 
INTO tbl_countries (CODE, NAME) VALUES ('CUW', 'Curacao') 
INTO tbl_countries (CODE, NAME) VALUES ('CYP', 'Cyprus') 
INTO tbl_countries (CODE, NAME) VALUES ('CZE', 'Czechia') 
INTO tbl_countries (CODE, NAME) VALUES ('DNK', 'Denmark') 
INTO tbl_countries (CODE, NAME) VALUES ('DJI', 'Djibouti') 
INTO tbl_countries (CODE, NAME) VALUES ('DMA', 'Dominica') 
INTO tbl_countries (CODE, NAME) VALUES ('DOM', 'Dominican Republic') 
INTO tbl_countries (CODE, NAME) VALUES ('ECU', 'Ecuador') 
INTO tbl_countries (CODE, NAME) VALUES ('EGY', 'Egypt, Arab Rep.') 
INTO tbl_countries (CODE, NAME) VALUES ('SLV', 'El Salvador') 
INTO tbl_countries (CODE, NAME) VALUES ('GNQ', 'Equatorial Guinea') 
INTO tbl_countries (CODE, NAME) VALUES ('ERI', 'Eritrea') 
INTO tbl_countries (CODE, NAME) VALUES ('EST', 'Estonia') 
INTO tbl_countries (CODE, NAME) VALUES ('SWZ', 'Eswatini') 
INTO tbl_countries (CODE, NAME) VALUES ('ETH', 'Ethiopia') 
INTO tbl_countries (CODE, NAME) VALUES ('FRO', 'Faroe Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('FJI', 'Fiji') 
INTO tbl_countries (CODE, NAME) VALUES ('FIN', 'Finland') 
INTO tbl_countries (CODE, NAME) VALUES ('FRA', 'France') 
INTO tbl_countries (CODE, NAME) VALUES ('PYF', 'French Polynesia') 
INTO tbl_countries (CODE, NAME) VALUES ('GAB', 'Gabon') 
INTO tbl_countries (CODE, NAME) VALUES ('GMB', 'Gambia, The') 
INTO tbl_countries (CODE, NAME) VALUES ('GEO', 'Georgia') 
INTO tbl_countries (CODE, NAME) VALUES ('DEU', 'Germany') 
INTO tbl_countries (CODE, NAME) VALUES ('GHA', 'Ghana') 
INTO tbl_countries (CODE, NAME) VALUES ('GIB', 'Gibraltar') 
INTO tbl_countries (CODE, NAME) VALUES ('GRC', 'Greece') 
INTO tbl_countries (CODE, NAME) VALUES ('GRL', 'Greenland') 
INTO tbl_countries (CODE, NAME) VALUES ('GRD', 'Grenada') 
INTO tbl_countries (CODE, NAME) VALUES ('GUM', 'Guam') 
INTO tbl_countries (CODE, NAME) VALUES ('GTM', 'Guatemala') 
INTO tbl_countries (CODE, NAME) VALUES ('GIN', 'Guinea') 
INTO tbl_countries (CODE, NAME) VALUES ('GNB', 'Guinea-Bissau') 
INTO tbl_countries (CODE, NAME) VALUES ('GUY', 'Guyana') 
INTO tbl_countries (CODE, NAME) VALUES ('HTI', 'Haiti') 
INTO tbl_countries (CODE, NAME) VALUES ('HND', 'Honduras') 
INTO tbl_countries (CODE, NAME) VALUES ('HKG', 'Hong Kong SAR, China') 
INTO tbl_countries (CODE, NAME) VALUES ('HUN', 'Hungary') 
INTO tbl_countries (CODE, NAME) VALUES ('ISL', 'Iceland') 
INTO tbl_countries (CODE, NAME) VALUES ('IND', 'India') 
INTO tbl_countries (CODE, NAME) VALUES ('IDN', 'Indonesia') 
INTO tbl_countries (CODE, NAME) VALUES ('IRN', 'Iran, Islamic Rep.') 
INTO tbl_countries (CODE, NAME) VALUES ('IRQ', 'Iraq') 
INTO tbl_countries (CODE, NAME) VALUES ('IRL', 'Ireland') 
INTO tbl_countries (CODE, NAME) VALUES ('IMN', 'Isle of Man') 
INTO tbl_countries (CODE, NAME) VALUES ('ISR', 'Israel') 
INTO tbl_countries (CODE, NAME) VALUES ('ITA', 'Italy') 
INTO tbl_countries (CODE, NAME) VALUES ('JAM', 'Jamaica') 
INTO tbl_countries (CODE, NAME) VALUES ('JPN', 'Japan') 
INTO tbl_countries (CODE, NAME) VALUES ('JOR', 'Jordan') 
INTO tbl_countries (CODE, NAME) VALUES ('KAZ', 'Kazakhstan') 
INTO tbl_countries (CODE, NAME) VALUES ('KEN', 'Kenya') 
INTO tbl_countries (CODE, NAME) VALUES ('KIR', 'Kiribati') 
INTO tbl_countries (CODE, NAME) VALUES ('PRK', 'North Korea') 
INTO tbl_countries (CODE, NAME) VALUES ('KOR', 'South Korea') 
INTO tbl_countries (CODE, NAME) VALUES ('XKX', 'Kosovo') 
INTO tbl_countries (CODE, NAME) VALUES ('KWT', 'Kuwait') 
INTO tbl_countries (CODE, NAME) VALUES ('KGZ', 'Kyrgyz Republic') 
INTO tbl_countries (CODE, NAME) VALUES ('LAO', 'Lao PDR') 
INTO tbl_countries (CODE, NAME) VALUES ('LVA', 'Latvia') 
INTO tbl_countries (CODE, NAME) VALUES ('LBN', 'Lebanon') 
INTO tbl_countries (CODE, NAME) VALUES ('LSO', 'Lesotho') 
INTO tbl_countries (CODE, NAME) VALUES ('LBR', 'Liberia') 
INTO tbl_countries (CODE, NAME) VALUES ('LBY', 'Libya') 
INTO tbl_countries (CODE, NAME) VALUES ('LIE', 'Liechtenstein') 
INTO tbl_countries (CODE, NAME) VALUES ('LTU', 'Lithuania') 
INTO tbl_countries (CODE, NAME) VALUES ('LUX', 'Luxembourg') 
INTO tbl_countries (CODE, NAME) VALUES ('MAC', 'Macao SAR, China') 
INTO tbl_countries (CODE, NAME) VALUES ('MDG', 'Madagascar') 
INTO tbl_countries (CODE, NAME) VALUES ('MWI', 'Malawi') 
INTO tbl_countries (CODE, NAME) VALUES ('MYS', 'Malaysia') 
INTO tbl_countries (CODE, NAME) VALUES ('MDV', 'Maldives') 
INTO tbl_countries (CODE, NAME) VALUES ('MLI', 'Mali') 
INTO tbl_countries (CODE, NAME) VALUES ('MLT', 'Malta') 
INTO tbl_countries (CODE, NAME) VALUES ('MHL', 'Marshall Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('MRT', 'Mauritania') 
INTO tbl_countries (CODE, NAME) VALUES ('MUS', 'Mauritius') 
INTO tbl_countries (CODE, NAME) VALUES ('MEX', 'Mexico') 
INTO tbl_countries (CODE, NAME) VALUES ('FSM', 'Micronesia, Fed. Sts.') 
INTO tbl_countries (CODE, NAME) VALUES ('MDA', 'Moldova') 
INTO tbl_countries (CODE, NAME) VALUES ('MCO', 'Monaco') 
INTO tbl_countries (CODE, NAME) VALUES ('MNG', 'Mongolia') 
INTO tbl_countries (CODE, NAME) VALUES ('MNE', 'Montenegro') 
INTO tbl_countries (CODE, NAME) VALUES ('MAR', 'Morocco') 
INTO tbl_countries (CODE, NAME) VALUES ('MOZ', 'Mozambique') 
INTO tbl_countries (CODE, NAME) VALUES ('MMR', 'Myanmar') 
INTO tbl_countries (CODE, NAME) VALUES ('NAM', 'Namibia') 
INTO tbl_countries (CODE, NAME) VALUES ('NRU', 'Nauru') 
INTO tbl_countries (CODE, NAME) VALUES ('NPL', 'Nepal') 
INTO tbl_countries (CODE, NAME) VALUES ('NLD', 'Netherlands') 
INTO tbl_countries (CODE, NAME) VALUES ('NCL', 'New Caledonia') 
INTO tbl_countries (CODE, NAME) VALUES ('NZL', 'New Zealand') 
INTO tbl_countries (CODE, NAME) VALUES ('NIC', 'Nicaragua') 
INTO tbl_countries (CODE, NAME) VALUES ('NER', 'Niger') 
INTO tbl_countries (CODE, NAME) VALUES ('NGA', 'Nigeria') 
INTO tbl_countries (CODE, NAME) VALUES ('MKD', 'North Macedonia') 
INTO tbl_countries (CODE, NAME) VALUES ('MNP', 'Northern Mariana Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('NOR', 'Norway') 
INTO tbl_countries (CODE, NAME) VALUES ('OMN', 'Oman') 
INTO tbl_countries (CODE, NAME) VALUES ('PAK', 'Pakistan') 
INTO tbl_countries (CODE, NAME) VALUES ('PLW', 'Palau') 
INTO tbl_countries (CODE, NAME) VALUES ('PAN', 'Panama') 
INTO tbl_countries (CODE, NAME) VALUES ('PNG', 'Papua New Guinea') 
INTO tbl_countries (CODE, NAME) VALUES ('PRY', 'Paraguay') 
INTO tbl_countries (CODE, NAME) VALUES ('PER', 'Peru') 
INTO tbl_countries (CODE, NAME) VALUES ('PHL', 'Philippines') 
INTO tbl_countries (CODE, NAME) VALUES ('POL', 'Poland') 
INTO tbl_countries (CODE, NAME) VALUES ('PRT', 'Portugal') 
INTO tbl_countries (CODE, NAME) VALUES ('PRI', 'Puerto Rico') 
INTO tbl_countries (CODE, NAME) VALUES ('QAT', 'Qatar') 
INTO tbl_countries (CODE, NAME) VALUES ('ROU', 'Romania') 
INTO tbl_countries (CODE, NAME) VALUES ('RUS', 'Russian Federation') 
INTO tbl_countries (CODE, NAME) VALUES ('RWA', 'Rwanda') 
INTO tbl_countries (CODE, NAME) VALUES ('WSM', 'Samoa') 
INTO tbl_countries (CODE, NAME) VALUES ('SMR', 'San Marino') 
INTO tbl_countries (CODE, NAME) VALUES ('STP', 'Sao Tome and Principe') 
INTO tbl_countries (CODE, NAME) VALUES ('SAU', 'Saudi Arabia') 
INTO tbl_countries (CODE, NAME) VALUES ('SEN', 'Senegal') 
INTO tbl_countries (CODE, NAME) VALUES ('SRB', 'Serbia') 
INTO tbl_countries (CODE, NAME) VALUES ('SYC', 'Seychelles') 
INTO tbl_countries (CODE, NAME) VALUES ('SLE', 'Sierra Leone') 
INTO tbl_countries (CODE, NAME) VALUES ('SGP', 'Singapore') 
INTO tbl_countries (CODE, NAME) VALUES ('SXM', 'Sint Maarten (Dutch part)') 
INTO tbl_countries (CODE, NAME) VALUES ('SVK', 'Slovak Republic') 
INTO tbl_countries (CODE, NAME) VALUES ('SVN', 'Slovenia') 
INTO tbl_countries (CODE, NAME) VALUES ('SLB', 'Solomon Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('SOM', 'Somalia') 
INTO tbl_countries (CODE, NAME) VALUES ('ZAF', 'South Africa') 
INTO tbl_countries (CODE, NAME) VALUES ('SSD', 'South Sudan') 
INTO tbl_countries (CODE, NAME) VALUES ('ESP', 'Spain') 
INTO tbl_countries (CODE, NAME) VALUES ('LKA', 'Sri Lanka') 
INTO tbl_countries (CODE, NAME) VALUES ('KNA', 'St. Kitts and Nevis') 
INTO tbl_countries (CODE, NAME) VALUES ('LCA', 'St. Lucia') 
INTO tbl_countries (CODE, NAME) VALUES ('MAF', 'St. Martin (French part)') 
INTO tbl_countries (CODE, NAME) VALUES ('VCT', 'St. Vincent and the Grenadines') 
INTO tbl_countries (CODE, NAME) VALUES ('SDN', 'Sudan') 
INTO tbl_countries (CODE, NAME) VALUES ('SUR', 'Suriname') 
INTO tbl_countries (CODE, NAME) VALUES ('SWE', 'Sweden') 
INTO tbl_countries (CODE, NAME) VALUES ('CHE', 'Switzerland') 
INTO tbl_countries (CODE, NAME) VALUES ('SYR', 'Syrian Arab Republic') 
INTO tbl_countries (CODE, NAME) VALUES ('TJK', 'Tajikistan') 
INTO tbl_countries (CODE, NAME) VALUES ('TZA', 'Tanzania') 
INTO tbl_countries (CODE, NAME) VALUES ('THA', 'Thailand') 
INTO tbl_countries (CODE, NAME) VALUES ('TLS', 'Timor-Leste') 
INTO tbl_countries (CODE, NAME) VALUES ('TGO', 'Togo') 
INTO tbl_countries (CODE, NAME) VALUES ('TON', 'Tonga') 
INTO tbl_countries (CODE, NAME) VALUES ('TTO', 'Trinidad and Tobago') 
INTO tbl_countries (CODE, NAME) VALUES ('TUN', 'Tunisia') 
INTO tbl_countries (CODE, NAME) VALUES ('TUR', 'Turkey') 
INTO tbl_countries (CODE, NAME) VALUES ('TKM', 'Turkmenistan') 
INTO tbl_countries (CODE, NAME) VALUES ('TCA', 'Turks and Caicos Islands') 
INTO tbl_countries (CODE, NAME) VALUES ('TUV', 'Tuvalu') 
INTO tbl_countries (CODE, NAME) VALUES ('UGA', 'Uganda') 
INTO tbl_countries (CODE, NAME) VALUES ('UKR', 'Ukraine') 
INTO tbl_countries (CODE, NAME) VALUES ('ARE', 'United Arab Emirates') 
INTO tbl_countries (CODE, NAME) VALUES ('GBR', 'United Kingdom') 
INTO tbl_countries (CODE, NAME) VALUES ('USA', 'United States') 
INTO tbl_countries (CODE, NAME) VALUES ('URY', 'Uruguay') 
INTO tbl_countries (CODE, NAME) VALUES ('UZB', 'Uzbekistan') 
INTO tbl_countries (CODE, NAME) VALUES ('VUT', 'Vanuatu') 
INTO tbl_countries (CODE, NAME) VALUES ('VEN', 'Venezuela, RB') 
INTO tbl_countries (CODE, NAME) VALUES ('VNM', 'Vietnam') 
INTO tbl_countries (CODE, NAME) VALUES ('VIR', 'Virgin Islands (U.S.)') 
INTO tbl_countries (CODE, NAME) VALUES ('PSE', 'West Bank and Gaza') 
INTO tbl_countries (CODE, NAME) VALUES ('YEM', 'Yemen, Rep.') 
INTO tbl_countries (CODE, NAME) VALUES ('ZMB', 'Zambia') 
INTO tbl_countries (CODE, NAME) VALUES ('ZWE', 'Zimbabwe') 
SELECT * FROM dual;